import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request';
import BlogCard from '../components/BlogCard';


const graphcms = new GraphQLClient('https://api-ap-south-1.graphcms.com/v2/cl4wufpfg0aee01ui5242b6ta/master');

const QUERY = gql`
{
  posts {
    id,
    title,
    datePublished,
    slug,
    content {
      html
    }
    author {
      name,
      avatar {
        url
      }
    }
    coverPhoto {
      publishedAt,
      createdBy {
        id
      },
      url
    }
  }
}
`;

export async function getStaticProps() {
  const {posts} = await graphcms.request(QUERY);

  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Mohamed Blogs</h1>

      <main className={styles.main}>
        {posts.map((post) => (
        <BlogCard title={post.title} author={post.author}
          coverPhoto={post.coverPhoto} key={post.id} 
          datePublished={post.datePublished} slug={post.slug} />
        ))}
        
      </main>

    </div>
  )
}
